// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OscarAPI.Models;

namespace OscarAPI.Migrations
{
    [DbContext(typeof(OscarAPIContext))]
    [Migration("20211007030416_SeedData1")]
    partial class SeedData1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("OscarAPI.Models.Nomination", b =>
                {
                    b.Property<int>("NominationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CategoryActive")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Film")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nominee")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Winner")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Year")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("NominationId");

                    b.ToTable("Nominations");

                    b.HasData(
                        new
                        {
                            NominationId = 1,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Nomadland",
                            Nominee = "Frances McDormand, Peter Spears, Mollye Asher, Dan Janvey, Chloé Zhao",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2020"
                        },
                        new
                        {
                            NominationId = 2,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Parasite",
                            Nominee = "Kwak Sin Ae and Bong Joon Ho",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2019"
                        },
                        new
                        {
                            NominationId = 3,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Green Book",
                            Nominee = "Jim Burke, Charles B. Wessler, Brian Currie, Peter Farrelly and Nick Vallelonga",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2018"
                        },
                        new
                        {
                            NominationId = 4,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "The Shape of Water",
                            Nominee = "Guillermo del Toro and J. Miles Dale",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2017"
                        },
                        new
                        {
                            NominationId = 5,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Moonlight",
                            Nominee = "Adele Romanski, Dede Gardner and Jeremy Kleiner",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2016"
                        },
                        new
                        {
                            NominationId = 6,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Spotlight",
                            Nominee = "Michael Sugar, Steve Golin, Nicole Rocklin and Blye Pagon Faust",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2015"
                        },
                        new
                        {
                            NominationId = 7,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Birdman or (The Unexpected Virtue of Ignorance)",
                            Nominee = "Alejandro G. Iñárritu, John Lesher and James W. Skotchdopole",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2014"
                        },
                        new
                        {
                            NominationId = 8,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "12 Years a Slave",
                            Nominee = "Brad Pitt, Dede Gardner, Jeremy Kleiner, Steve McQueen and Anthony Katagas",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2013"
                        },
                        new
                        {
                            NominationId = 9,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Argo",
                            Nominee = "Grant Heslov, Ben Affleck and George Clooney",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2012"
                        },
                        new
                        {
                            NominationId = 10,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "The Artist",
                            Nominee = "Thomas Langmann",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2011"
                        },
                        new
                        {
                            NominationId = 11,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "The King's Speech",
                            Nominee = "Iain Canning, Emile Sherman and Gareth Unwin",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2010"
                        },
                        new
                        {
                            NominationId = 12,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "The Hurt Locker",
                            Nominee = "Kathryn Bigelow, Mark Boal, Nicolas Chartier and Greg Shapiro",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2009"
                        },
                        new
                        {
                            NominationId = 13,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Slumdog Millionaire",
                            Nominee = "Christian Colson",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2008"
                        },
                        new
                        {
                            NominationId = 14,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "No Country for Old Men",
                            Nominee = "Scott Rudin, Ethan Coen and Joel Coen",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2007"
                        },
                        new
                        {
                            NominationId = 15,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "The Departed",
                            Nominee = "Graham King",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2006"
                        },
                        new
                        {
                            NominationId = 16,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Crash",
                            Nominee = "Paul Haggis and Cathy Schulman",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2005"
                        },
                        new
                        {
                            NominationId = 17,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Million Dollar Baby",
                            Nominee = "Clint Eastwood, Albert S. Ruddy and Tom Rosenberg",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2004"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
