// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OscarAPI.Models;

namespace OscarAPI.Migrations
{
    [DbContext(typeof(OscarAPIContext))]
    [Migration("20211007065137_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("OscarAPI.Models.Nomination", b =>
                {
                    b.Property<int>("NominationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CategoryActive")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Film")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nominee")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Winner")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("NominationId");

                    b.ToTable("Nominations");

                    b.HasData(
                        new
                        {
                            NominationId = 1,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Nomadland",
                            Nominee = "Frances McDormand, Peter Spears, Mollye Asher, Dan Janvey, Chloé Zhao",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2020"
                        },
                        new
                        {
                            NominationId = 2,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Parasite",
                            Nominee = "Kwak Sin Ae and Bong Joon Ho",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2019"
                        },
                        new
                        {
                            NominationId = 3,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Green Book",
                            Nominee = "Jim Burke, Charles B. Wessler, Brian Currie, Peter Farrelly and Nick Vallelonga",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2018"
                        },
                        new
                        {
                            NominationId = 4,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "The Shape of Water",
                            Nominee = "Guillermo del Toro and J. Miles Dale",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2017"
                        },
                        new
                        {
                            NominationId = 5,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Moonlight",
                            Nominee = "Adele Romanski, Dede Gardner and Jeremy Kleiner",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2016"
                        },
                        new
                        {
                            NominationId = 6,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Spotlight",
                            Nominee = "Michael Sugar, Steve Golin, Nicole Rocklin and Blye Pagon Faust",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2015"
                        },
                        new
                        {
                            NominationId = 7,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Birdman or (The Unexpected Virtue of Ignorance)",
                            Nominee = "Alejandro G. Iñárritu, John Lesher and James W. Skotchdopole",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2014"
                        },
                        new
                        {
                            NominationId = 8,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "12 Years a Slave",
                            Nominee = "Brad Pitt, Dede Gardner, Jeremy Kleiner, Steve McQueen and Anthony Katagas",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2013"
                        },
                        new
                        {
                            NominationId = 9,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Argo",
                            Nominee = "Grant Heslov, Ben Affleck and George Clooney",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2012"
                        },
                        new
                        {
                            NominationId = 10,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "The Artist",
                            Nominee = "Thomas Langmann",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2011"
                        },
                        new
                        {
                            NominationId = 11,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "The King's Speech",
                            Nominee = "Iain Canning, Emile Sherman and Gareth Unwin",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2010"
                        },
                        new
                        {
                            NominationId = 12,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "The Hurt Locker",
                            Nominee = "Kathryn Bigelow, Mark Boal, Nicolas Chartier and Greg Shapiro",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2009"
                        },
                        new
                        {
                            NominationId = 13,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Slumdog Millionaire",
                            Nominee = "Christian Colson",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2008"
                        },
                        new
                        {
                            NominationId = 14,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "No Country for Old Men",
                            Nominee = "Scott Rudin, Ethan Coen and Joel Coen",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2007"
                        },
                        new
                        {
                            NominationId = 15,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "The Departed",
                            Nominee = "Graham King",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2006"
                        },
                        new
                        {
                            NominationId = 16,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Crash",
                            Nominee = "Paul Haggis and Cathy Schulman",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2005"
                        },
                        new
                        {
                            NominationId = 17,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Million Dollar Baby",
                            Nominee = "Clint Eastwood, Albert S. Ruddy and Tom Rosenberg",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2004"
                        },
                        new
                        {
                            NominationId = 18,
                            Category = "Directing",
                            CategoryActive = "Yes",
                            Film = "Nomadland",
                            Nominee = "Chloé Zhao",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2020"
                        },
                        new
                        {
                            NominationId = 19,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "The Lord of the Rings: The Return of the King",
                            Nominee = "Barrie M. Osborne, Peter Jackson and Fran Walsh",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2003"
                        },
                        new
                        {
                            NominationId = 20,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Chicago",
                            Nominee = "Martin Richards",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2002"
                        },
                        new
                        {
                            NominationId = 21,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "A Beautiful Mind",
                            Nominee = "Brian Grazer and Ron Howard",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2001"
                        },
                        new
                        {
                            NominationId = 22,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Gladiator",
                            Nominee = "Douglas Wick, David Franzoni and Branko Lustig",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "2000"
                        },
                        new
                        {
                            NominationId = 23,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "American Beauty",
                            Nominee = "Bruce Cohen and Dan Jinks",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1999"
                        },
                        new
                        {
                            NominationId = 24,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Shakespeare in Love",
                            Nominee = "David Parfitt, Donna Gigliotti, Harvey Weinstein, Edward Zwick and Marc Norman",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1998"
                        },
                        new
                        {
                            NominationId = 25,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Titanic",
                            Nominee = "James Cameron and Jon Landau",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1997"
                        },
                        new
                        {
                            NominationId = 26,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "The English Patient",
                            Nominee = "Saul Zaentz",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1996"
                        },
                        new
                        {
                            NominationId = 27,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Braveheart",
                            Nominee = "Mel Gibson, Alan Ladd, Jr. and Bruce Davey",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1995"
                        },
                        new
                        {
                            NominationId = 28,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Forrest Gump",
                            Nominee = "Wendy Finerman, Steve Tisch and Steve Starkey",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1994"
                        },
                        new
                        {
                            NominationId = 29,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Schindler's List",
                            Nominee = "Steven Spielberg, Gerald R. Molen and Branko Lustig",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1993"
                        },
                        new
                        {
                            NominationId = 30,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Unforgiven",
                            Nominee = "Clint Eastwood",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1992"
                        },
                        new
                        {
                            NominationId = 31,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "The Silence of the Lambs",
                            Nominee = "Edward Saxon, Kenneth Utt and Ron Bozman",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1991"
                        },
                        new
                        {
                            NominationId = 32,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Dances With Wolves",
                            Nominee = "Jim Wilson and Kevin Costner",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1990"
                        },
                        new
                        {
                            NominationId = 33,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Driving Miss Daisy",
                            Nominee = "Richard D. Zanuck and Lili Fini Zanuck",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1989"
                        },
                        new
                        {
                            NominationId = 34,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Rain Man",
                            Nominee = "Mark Johnson",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1988"
                        },
                        new
                        {
                            NominationId = 35,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "The Last Emperor",
                            Nominee = "Jeremy Thomas",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1987"
                        },
                        new
                        {
                            NominationId = 36,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Platoon",
                            Nominee = "Arnold Kopelson",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1986"
                        },
                        new
                        {
                            NominationId = 37,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Out of Africa",
                            Nominee = "Sydney Pollack",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1985"
                        },
                        new
                        {
                            NominationId = 38,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Amadeus",
                            Nominee = "Saul Zaentz",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1984"
                        },
                        new
                        {
                            NominationId = 39,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Terms of Endearment",
                            Nominee = "James L. Brooks",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1983"
                        },
                        new
                        {
                            NominationId = 40,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Ghandi",
                            Nominee = "Richard Attenborough",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1982"
                        },
                        new
                        {
                            NominationId = 41,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Chariots of Fire",
                            Nominee = "David Puttnam",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1981"
                        },
                        new
                        {
                            NominationId = 42,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Ordinary People",
                            Nominee = "Ronald L. Schwary",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1980"
                        },
                        new
                        {
                            NominationId = 43,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Kramer vs. Kramer",
                            Nominee = "Stanley R. Jaffe",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1979"
                        },
                        new
                        {
                            NominationId = 44,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "The Deer Hunter",
                            Nominee = "Barry Spikings, Michael Deeley, Michael Cimino and John Peverall",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1978"
                        },
                        new
                        {
                            NominationId = 45,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Annie Hall",
                            Nominee = "Charles H. Joffe",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1977"
                        },
                        new
                        {
                            NominationId = 46,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Rocky",
                            Nominee = "Irwin Winkler and Robert Chartoff",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1976"
                        },
                        new
                        {
                            NominationId = 47,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "One Flew over the Cuckoo's Nest",
                            Nominee = "Saul Zaentz and Michael Douglas",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1975"
                        },
                        new
                        {
                            NominationId = 48,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "The Godfather Part II",
                            Nominee = "Francis Ford Coppola, Producer; Gray Frederickson and Fred Roos",
                            Notes = "Listed as Co-Producers",
                            Winner = "Yes",
                            Year = "1974"
                        },
                        new
                        {
                            NominationId = 49,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "The Sting",
                            Nominee = "Tony Bill, Michael Phillips and Julia Phillips",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1973"
                        },
                        new
                        {
                            NominationId = 50,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "The Godfather",
                            Nominee = "Albert S. Ruddy",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1972"
                        },
                        new
                        {
                            NominationId = 51,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "The French Connection",
                            Nominee = "Philip D'Antoni",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1971"
                        },
                        new
                        {
                            NominationId = 52,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Patton",
                            Nominee = "Frank McCarthy",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1970"
                        },
                        new
                        {
                            NominationId = 53,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Midnight Cowboy",
                            Nominee = "Jerome Hellman",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1969"
                        },
                        new
                        {
                            NominationId = 54,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Oliver!",
                            Nominee = "John Woolf",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1968"
                        },
                        new
                        {
                            NominationId = 55,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "In the Heat of the Night",
                            Nominee = "Walter Mirisch",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1967"
                        },
                        new
                        {
                            NominationId = 56,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "A Man for all Seasons",
                            Nominee = "Fred Zinnemann",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1966"
                        },
                        new
                        {
                            NominationId = 57,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "The Sound of Music",
                            Nominee = "Robert Wise",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1965"
                        },
                        new
                        {
                            NominationId = 58,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "My Fair Lady",
                            Nominee = "Jack L. Warner",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1964"
                        },
                        new
                        {
                            NominationId = 59,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Tom Jones",
                            Nominee = "Tony Richardson",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1963"
                        },
                        new
                        {
                            NominationId = 60,
                            Category = "Best Picture",
                            CategoryActive = "Yes",
                            Film = "Lawrence of Arabia",
                            Nominee = "Sam Spiegel",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1962"
                        },
                        new
                        {
                            NominationId = 61,
                            Category = "Best Motion Picture",
                            CategoryActive = "Yes",
                            Film = "West Side Story",
                            Nominee = "Robert Wise",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1961"
                        },
                        new
                        {
                            NominationId = 62,
                            Category = "Best Motion Picture",
                            CategoryActive = "Yes",
                            Film = "The Apartment",
                            Nominee = "Billy Wilder",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1960"
                        },
                        new
                        {
                            NominationId = 63,
                            Category = "Best Motion Picture",
                            CategoryActive = "Yes",
                            Film = "Ben-Hur",
                            Nominee = "Sam Zimbalist",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1959"
                        },
                        new
                        {
                            NominationId = 64,
                            Category = "Best Motion Picture",
                            CategoryActive = "Yes",
                            Film = "Gigi",
                            Nominee = "Arthur Freed",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1958"
                        },
                        new
                        {
                            NominationId = 65,
                            Category = "Best Motion Picture",
                            CategoryActive = "Yes",
                            Film = "The Bridge on the River Kwai",
                            Nominee = "Sam Spiegel",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1957"
                        },
                        new
                        {
                            NominationId = 66,
                            Category = "Best Motion Picture",
                            CategoryActive = "Yes",
                            Film = "Around the World in 80 Days",
                            Nominee = "Michael Todd",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1956"
                        },
                        new
                        {
                            NominationId = 67,
                            Category = "Best Motion Picture",
                            CategoryActive = "Yes",
                            Film = "Marty",
                            Nominee = "Harold Hecht",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1955"
                        },
                        new
                        {
                            NominationId = 68,
                            Category = "Best Motion Picture",
                            CategoryActive = "Yes",
                            Film = "On the Waterfront",
                            Nominee = "Sam Spiegel",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1954"
                        },
                        new
                        {
                            NominationId = 69,
                            Category = "Best Motion Picture",
                            CategoryActive = "Yes",
                            Film = "From Here to Eternity",
                            Nominee = "Buddy Adler,",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1953"
                        },
                        new
                        {
                            NominationId = 70,
                            Category = "Best Motion Picture",
                            CategoryActive = "Yes",
                            Film = "The Greatest Show on Earth",
                            Nominee = "Cecil B. DeMille",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1952"
                        },
                        new
                        {
                            NominationId = 71,
                            Category = "Best Motion Picture",
                            CategoryActive = "Yes",
                            Film = "An American in Paris",
                            Nominee = "Arthur Freed",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1951"
                        },
                        new
                        {
                            NominationId = 72,
                            Category = "Best Motion Picture",
                            CategoryActive = "Yes",
                            Film = "All About Eve",
                            Nominee = "20th Century-Fox ",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1950"
                        },
                        new
                        {
                            NominationId = 73,
                            Category = "Best Motion Picture",
                            CategoryActive = "Yes",
                            Film = "All The King's Men",
                            Nominee = "Robert Rossen Productions",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1949"
                        },
                        new
                        {
                            NominationId = 74,
                            Category = "Best Motion Picture",
                            CategoryActive = "Yes",
                            Film = "Hamlet",
                            Nominee = "J. Arthur Rank-Two Cities Films",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1948"
                        },
                        new
                        {
                            NominationId = 75,
                            Category = "Best Motion Picture",
                            CategoryActive = "Yes",
                            Film = "Gentleman's Agreement",
                            Nominee = "20th Century-Fox ",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1947"
                        },
                        new
                        {
                            NominationId = 76,
                            Category = "Best Motion Picture",
                            CategoryActive = "Yes",
                            Film = "The Best Years of Our Lives",
                            Nominee = "Samuel Goldwyn Productions",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1946"
                        },
                        new
                        {
                            NominationId = 77,
                            Category = "Best Motion Picture",
                            CategoryActive = "Yes",
                            Film = "The Lost Weekend",
                            Nominee = "Paramount",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1945"
                        },
                        new
                        {
                            NominationId = 78,
                            Category = "Best Motion Picture",
                            CategoryActive = "Yes",
                            Film = "Going My Way",
                            Nominee = "Paramount",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1944"
                        },
                        new
                        {
                            NominationId = 79,
                            Category = "Outstanding Motion Picture",
                            CategoryActive = "Yes",
                            Film = "Casablanca",
                            Nominee = "Warner Bros.",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1943"
                        },
                        new
                        {
                            NominationId = 80,
                            Category = "Outstanding Motion Picture",
                            CategoryActive = "Yes",
                            Film = "Mrs. Miniver",
                            Nominee = "Metro-Goldwyn-Mayer",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1942"
                        },
                        new
                        {
                            NominationId = 81,
                            Category = "Outstanding Motion Picture",
                            CategoryActive = "Yes",
                            Film = "How Green Was My Valley",
                            Nominee = "20th Century-Fox ",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1941"
                        },
                        new
                        {
                            NominationId = 84,
                            Category = "Outstanding Production",
                            CategoryActive = "Yes",
                            Film = "Rebecca",
                            Nominee = "Selznick International Pictures",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1940"
                        },
                        new
                        {
                            NominationId = 85,
                            Category = "Outstanding Production",
                            CategoryActive = "Yes",
                            Film = "Gone with the Wind",
                            Nominee = "Selznick International Pictures",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1939"
                        },
                        new
                        {
                            NominationId = 86,
                            Category = "Outstanding Production",
                            CategoryActive = "Yes",
                            Film = "You Can't Take It With You",
                            Nominee = "Columbia",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1938"
                        },
                        new
                        {
                            NominationId = 87,
                            Category = "Outstanding Production",
                            CategoryActive = "Yes",
                            Film = "The Life of Emilie Zola",
                            Nominee = "Warner Bros.",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1937"
                        },
                        new
                        {
                            NominationId = 88,
                            Category = "Outstanding Production",
                            CategoryActive = "Yes",
                            Film = "The Great Ziegfeld",
                            Nominee = "Metro-Goldwyn-Mayer",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1936"
                        },
                        new
                        {
                            NominationId = 89,
                            Category = "Outstanding Production",
                            CategoryActive = "Yes",
                            Film = "Mutiny on the Bounty",
                            Nominee = "Metro-Goldwyn-Mayer",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1935"
                        },
                        new
                        {
                            NominationId = 90,
                            Category = "Outstanding Production",
                            CategoryActive = "Yes",
                            Film = "It Happened One Night",
                            Nominee = "Columbia",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1934"
                        },
                        new
                        {
                            NominationId = 91,
                            Category = "Outstanding Production",
                            CategoryActive = "Yes",
                            Film = "Cavalcade",
                            Nominee = "Fox",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1932/1933"
                        },
                        new
                        {
                            NominationId = 92,
                            Category = "Outstanding Production",
                            CategoryActive = "Yes",
                            Film = "Grand Hotel",
                            Nominee = "Metro-Goldwyn-Mayer",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1931/1932"
                        },
                        new
                        {
                            NominationId = 93,
                            Category = "Outstanding Production",
                            CategoryActive = "Yes",
                            Film = "Cimarron",
                            Nominee = "RKO Radio",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1930/1931"
                        },
                        new
                        {
                            NominationId = 94,
                            Category = "Outstanding Production",
                            CategoryActive = "Yes",
                            Film = "All Quiet on the Western Front",
                            Nominee = "Universal",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1929/1930"
                        },
                        new
                        {
                            NominationId = 95,
                            Category = "Outstanding Production",
                            CategoryActive = "Yes",
                            Film = "The Broadway Melody",
                            Nominee = "Metro-Goldwyn-Mayer",
                            Notes = "NOT AN OFFICIAL NOMINATION. There were no announcements of nominations, no certificates of nomination or honorable mention, and only the winners were revealed during the awards banquet on April 3, 1930.",
                            Winner = "Yes",
                            Year = "1928/1929"
                        },
                        new
                        {
                            NominationId = 96,
                            Category = "Outstanding Picture",
                            CategoryActive = "Yes",
                            Film = "Wings",
                            Nominee = "Paramount Famous Lasky",
                            Notes = "N/A",
                            Winner = "Yes",
                            Year = "1927/1928"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
